In [1]:
#Given the code contain few example of about matrix opertaion and somr linear-alzebra concept
import numpy as np


In [2]:
#41
arr = np.array([[1, 2, 3], [4, 5, 6]])
a,b=arr.shape
for i in range(b):
    print(i,"column mean=",arr[:,i].mean())
    

0 column mean= 2.5
1 column mean= 3.5
2 column mean= 4.5


In [3]:
#42
arr = np.array([[1, 2, 3], [4, 5, 6]])
a,b=arr.shape
for i in range(a):
    print(i,"row have maximun element",arr[i].max())

0 row have maximun element 3
1 row have maximun element 6


In [4]:
#43
arr = np.array([[1, 2, 3], [4, 5, 6]])
a,b=arr.shape
lmax=[]
for i in range(b):
    lmax.append(arr[:,i].max())
lmax
count=0
l2=[]
for i in range (b):
    for j in range (a):
        if (lmax[i]==arr[j,i]):
            l2.append(list([i,j]))
l2

[[0, 1], [1, 1], [2, 1]]

In [5]:
#44
#costum function to sum along rows
arr = np.array([[1, 2, 3], [4, 5, 6]])
def sum_row(a,row):
    l=[]
    for i in range (row):
        l.append(a[i].sum())
    return l
sum_row(arr,2)

[6, 15]

In [6]:
#45
arr = np.array([[2, 4, 6], [3, 5, 7]])
a,b=arr.shape
c=np.zeros((a,b))
for i in range (a):
    for j in range (b):
        if arr[i][j]%2==0:
            c[i][j]+=1
for i in range (b):
    if 0 in arr[:,i]:print("fg")
    else:print(False)

False
False
False


In [7]:
#46
original_array = np.array([1, 2, 3, 4, 5, 6])
original_array.reshape(2,-1)


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#48
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
np.concatenate((array1,array2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
#49
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def splits(array,axis):
    a,b=array.shape
    l =[]
    if axis == 0:
        for i in range(a):
            l.append(list(array[i]))
    if axis==1:
        for i in range(b):
            l.append(list(array[:,i]))
    return l
splits(original_array,1)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [10]:
#50
def insertion(array,index,value):

    c=np.insert(array,index,value)
    return c
def delition(array,index):
    return np.delete(array,index)
    
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
insertion(original_array,2,10)
insertion(original_array,4,11)
delition(original_array,1)
delition(original_array,3)

array([1, 2, 3, 5])

In [11]:
#51
a=np.random.randint(1,10,size=10)
b=np.array([1,2,3,4,5,6,7,8,9,10])
a+b

array([ 5,  9,  7,  9,  7,  7,  8, 14, 17, 12])

In [12]:
#52
arr1=np.array([ i for i in range(10,0,-1)])
arr2=np.array([i for i in range(1,11,1)])
arr1-arr2

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

In [13]:
#53
arr1=np.random.randint(1,5,size=(3,4))
arr2=np.random.randint(1,5,size=(3,4))
arr1*arr2

array([[ 4,  2,  3, 12],
       [ 1,  1,  3,  8],
       [ 2,  4,  4,  3]])

In [14]:
#54
arr1=np.array( [i for i in range(2,11,2)])
arr2=np.random.randint(1,5,size=5)
arr1/arr2

array([ 2.        ,  1.33333333,  1.5       ,  4.        , 10.        ])

In [15]:
#55
arr1=np.array([i for i in range(1,6)])
arr2=np.array([i for i in range(5,0,-1)])
arr1**arr2


array([ 1, 16, 27, 16,  5])

In [16]:
#56
def count(arr,str):
    count=0
    for i in arr:
        if i==str:
            count +=1
    return count
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
count(arr,'hello')

3

In [17]:
#57
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extract_uper(array):
    l=[]
    for i in array:
        for j in i:
            if j.isupper() == True:l.append(j)
    return l
extract_uper(arr)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

In [18]:
#58
def replace(arr,str):
    for i in range(len(arr)):
        if str in arr[i]: arr[i]="Changed"
    return arr    
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
replace(arr,"apple")  

array(['Changed', 'banana', 'grape', 'Changed'], dtype='<U9')

In [19]:
#59
def conca(arr1,arr2):
    l=len(arr1)
    l1=[]
    for i in range(l):
        l1.append(arr1[i]+arr2[i])
    return(np.array(l1))
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
conca(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [20]:
def largelength(array):
    l=[]
    for i in array:
        l.append(len(i))
    return max(l)
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
largelength(arr)

9

In [21]:
#61
a=np.random.randint(1,100,size=100)
print(np.mean(a))
print(np.median(a))
print(np.std(a))


53.53
57.5
29.316703429956107


In [22]:
#61
a=np.random.randint(1,100,size=50)
print(np.percentile(a,25)) #25 th persentile
print(np.percentile(a,75)) #75 th persentile

15.25
74.75


In [23]:
#64
a=np.random.randint(1,10,size=(4,3))
b=np.random.randint(1,10,size=(3,5))
np.dot(a,b)

array([[ 35,  51,  37,  65,  51],
       [ 94, 126,  99, 149, 117],
       [ 71,  85,  83,  93,  75],
       [ 61,  91,  60, 116,  90]])

In [24]:
#65
a=np.random.randint(10,1000,size=50)
print(np.percentile(a,10))
print(np.percentile(a,50))
print(np.percentile(a,90))

138.70000000000002
508.0
875.5


In [25]:
#67
a=np.array([33,5,88,56,3,28,46])
np.short(a)

array([33,  5, 88, 56,  3, 28, 46], dtype=int16)

In [26]:
#68
def filter_20(arr):
    l=[]
    for i in arr:
        if i>=20:l.append(i)
    return np.array(l)
arr = np.array([12, 25, 6, 42, 8, 30])
filter_20(arr)

array([25, 42, 30])

In [27]:
#69
def filter_divisible_3(arr):
    l=[]
    for i in arr:
        if i%3==0: l.append(i)
    return np.array(l)
arr = np.array([1, 5, 8, 12, 15])
filter_divisible_3(arr)


array([12, 15])

In [28]:
#70
def filter_20_40(arr):
    l=[]
    for i in arr:
        if i>=20 and i<=40 : l.append(i)
    return l
arr = np.array([10, 20, 30, 40, 50])
filter_20_40(arr)

[20, 30, 40]

In [29]:
#71
arr = np.array([1, 2, 3])
for i in arr:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [30]:
#72
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

In [31]:
#73
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

In [32]:
#82
c=np.random.randint(1,4,size=(3,2))
d=np.random.randint(1,4,size=(2,4))
np.dot(c,d)

array([[10,  5, 13, 13],
       [ 6,  3,  8,  8],
       [ 8,  4, 11, 11]])

In [33]:
#83
e=np.random.randint(1,5,size=(3,6))
e.T

array([[1, 3, 1],
       [2, 1, 4],
       [3, 1, 4],
       [1, 4, 3],
       [3, 1, 3],
       [4, 2, 3]])

In [34]:
#84
f=np.random.randint(1,5,size=(4,4))
np.linalg.det(f)

-65.99999999999997

In [35]:
#85
g=np.random.randint(1,5,size=(3,3))
np.linalg.inv(g)

array([[-0.5   , -0.4375,  0.8125],
       [ 0.5   ,  0.8125, -0.9375],
       [ 0.    , -0.5   ,  0.5   ]])